/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/Home/index'
import { Route as ProductsCategoryIdRouteImport } from './routes/products/$categoryId'
import { Route as ProductsProductDetailsProductIdRouteImport } from './routes/products/productDetails/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/Home/',
  path: '/Home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryIdRoute = ProductsCategoryIdRouteImport.update({
  id: '/products/$categoryId',
  path: '/products/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductDetailsProductIdRoute =
  ProductsProductDetailsProductIdRouteImport.update({
    id: '/products/productDetails/$productId',
    path: '/products/productDetails/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products/$categoryId': typeof ProductsCategoryIdRoute
  '/Home': typeof HomeIndexRoute
  '/products/productDetails/$productId': typeof ProductsProductDetailsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products/$categoryId': typeof ProductsCategoryIdRoute
  '/Home': typeof HomeIndexRoute
  '/products/productDetails/$productId': typeof ProductsProductDetailsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products/$categoryId': typeof ProductsCategoryIdRoute
  '/Home/': typeof HomeIndexRoute
  '/products/productDetails/$productId': typeof ProductsProductDetailsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products/$categoryId'
    | '/Home'
    | '/products/productDetails/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products/$categoryId'
    | '/Home'
    | '/products/productDetails/$productId'
  id:
    | '__root__'
    | '/'
    | '/products/$categoryId'
    | '/Home/'
    | '/products/productDetails/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsCategoryIdRoute: typeof ProductsCategoryIdRoute
  HomeIndexRoute: typeof HomeIndexRoute
  ProductsProductDetailsProductIdRoute: typeof ProductsProductDetailsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Home/': {
      id: '/Home/'
      path: '/Home'
      fullPath: '/Home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$categoryId': {
      id: '/products/$categoryId'
      path: '/products/$categoryId'
      fullPath: '/products/$categoryId'
      preLoaderRoute: typeof ProductsCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/productDetails/$productId': {
      id: '/products/productDetails/$productId'
      path: '/products/productDetails/$productId'
      fullPath: '/products/productDetails/$productId'
      preLoaderRoute: typeof ProductsProductDetailsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsCategoryIdRoute: ProductsCategoryIdRoute,
  HomeIndexRoute: HomeIndexRoute,
  ProductsProductDetailsProductIdRoute: ProductsProductDetailsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
